version: '3.8'
services:
  movies:
    image: nikhilkp08/movies1:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: nikhilkp08/train1:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: nikhilkp08/dth1:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: nikhilkp08/recharge1:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
